#!/usr/bin/env python3
"""Build a single-file AGILLM runtime with the attention backend folded in.

This tool never modifies the source runtime in place.  It makes the mask
producer and attention consumer changes as one atomic candidate, compiles the
result, and writes a machine-readable receipt.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import stat
import tempfile
import time
from typing import Dict, Tuple


BUILDER_SCHEMA = "agillm.attention.runtime-builder.v1"
BEGIN_SENTINEL = "# ===== BEGIN AGILLM ATTENTION BACKEND V1 (FOLDED) ====="
END_SENTINEL = "# ===== END AGILLM ATTENTION BACKEND V1 (FOLDED) ====="
CALL_SENTINEL = "# AGILLM44-ATTENTION-DISPATCH-V1"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def replace_exact(text: str, old: str, new: str, expected: int, label: str) -> Tuple[str, int]:
    count = text.count(old)
    if count != expected:
        raise RuntimeError(
            "%s replacement expected %d occurrence(s), found %d" %
            (label, expected, count)
        )
    return text.replace(old, new), count


def folded_backend_source(backend_source: str, backend_sha: str) -> str:
    module_name = "_agillm_attention_backend_v1_%s" % backend_sha[:12]
    return f'''{BEGIN_SENTINEL}
# Generated by tools/build_runtime_candidate.py.  The source is kept in
# agillm_attention/backend.py and folded here so the trainer remains a genuine
# single-file deployment artifact.
_AGILLM_ATTENTION_BACKEND_SOURCE_SHA256 = {backend_sha!r}
_AGILLM_ATTENTION_BACKEND_SOURCE = {backend_source!r}
_AGILLM_ATTENTION_MODULE_NAME = {module_name!r}
_agillm_attention_module = _agillm41_sys.modules.get(_AGILLM_ATTENTION_MODULE_NAME)
if _agillm_attention_module is None:
    _agillm_attention_module = _agillm41_types.ModuleType(_AGILLM_ATTENTION_MODULE_NAME)
    _agillm_attention_module.__file__ = __file__ + "#agillm_attention/backend.py"
    _agillm_attention_module.__package__ = ""
    _agillm41_sys.modules[_AGILLM_ATTENTION_MODULE_NAME] = _agillm_attention_module
    exec(
        compile(
            _AGILLM_ATTENTION_BACKEND_SOURCE,
            _agillm_attention_module.__file__,
            "exec",
        ),
        _agillm_attention_module.__dict__,
    )
_AgillmAttentionMaskSpec = _agillm_attention_module.MaskSpec
_agillm_attention = _agillm_attention_module.attention
{END_SENTINEL}

'''


def dispatch_block() -> str:
    return '''        attn_mask = mask
        _agillm_mask_spec = None
        _agillm_score_bias = None
        if self.attn_backend == "sdpa" and _is_structured_attention_mask(attn_mask):
            _agillm_mask_spec = _AgillmAttentionMaskSpec(
                kind=attn_mask.kind,
                q_len=int(attn_mask.q_len),
                kv_len=int(attn_mask.k_len),
                query_base=int(attn_mask.query_base),
                block_size=int(attn_mask.block),
            )
            attn_mask = None
        elif self.attn_backend != "sublinear" and _is_structured_attention_mask(attn_mask):
            attn_mask = attn_mask.to_dense(device=q.device, dtype=q.dtype)
        # AGILLM43-ALIBI-ZERO-SKIP-20260823: alibi_scale 0.0 makes the bias an
        # exact-zero (1,H,T,T) tensor; building/adding it only widens the mask
        # and burns DRAM bandwidth. Skipping is bitwise-identical.
        if self.attn_backend != "sublinear" and self.use_relpos and rel_bias_tokens is not None and float(_AGILLM_ALIBI_SCALE) != 0.0:
            rel = alibi_bias(self.h, rel_bias_tokens)[:, :, -q.size(2):, :].to(device=q.device, dtype=q.dtype)
            if self.attn_backend == "sdpa" and _agillm_mask_spec is not None:
                _agillm_score_bias = rel
            else:
                attn_mask = rel if attn_mask is None else attn_mask + rel
        if self.attn_backend == "sdpa" and attn_mask is not None and attn_mask.dtype != torch.bool and attn_mask.dtype != q.dtype:
            attn_mask = attn_mask.to(dtype=q.dtype)
        if self.attn_backend == "sdpa":
            # AGILLM44-ATTENTION-DISPATCH-V1: native causal SDPA on eligible
            # square masks; exact dense fallback on torch 2.2; optional fused
            # structured SAT on newer isolated runtimes with FlexAttention.
            _agillm_force_backend = str(
                os.environ.get("AGILLM_ATTENTION_FORCE_BACKEND", "") or ""
            ).strip().lower() or None
            _agillm_prefer_flex = str(
                os.environ.get("AGILLM_ATTENTION_PREFER_FLEX", "1") or "1"
            ).strip().lower() not in {"0", "false", "no", "off"}
            z = _agillm_attention(
                q,
                k,
                v,
                mask_spec=_agillm_mask_spec,
                attn_mask=attn_mask,
                score_bias=_agillm_score_bias,
                dropout_p=0.0,
                scale=1.0 / math.sqrt(self.dk),
                prefer_flex=_agillm_prefer_flex,
                force_backend=_agillm_force_backend,
                compile_flex=True,
            )
'''


def helper_block() -> str:
    return '''def _dblock_causal_mask(args, n):
    """Exact DBlock causal rule, kept symbolic for optimized SDPA dispatch."""
    if (str(getattr(args, "attn_backend", "") or "").lower() == "sdpa"
            and float(_AGILLM_ALIBI_SCALE) == 0.0):
        return StructuredAttentionMask(
            "causal", q_len=int(n), k_len=int(n), query_base=0
        )
    return causal_mask(int(n), structured=use_structured_masks(args))


def _dblock_sat_mask(args, n, block=SAT_BLOCK):
    """Exact fixed-block SAT rule, symbolic when the backend can consume it."""
    if (str(getattr(args, "attn_backend", "") or "").lower() == "sdpa"
            and float(_AGILLM_ALIBI_SCALE) == 0.0):
        return StructuredAttentionMask(
            "sat",
            q_len=int(n),
            k_len=int(n),
            query_base=0,
            block=max(1, int(block)),
        )
    return sat_mask(
        int(n), block=max(1, int(block)), structured=use_structured_masks(args)
    )


'''


def patch_runtime(source: str, backend_source: str, backend_sha: str) -> Tuple[str, Dict[str, int]]:
    if BEGIN_SENTINEL in source or CALL_SENTINEL in source:
        raise RuntimeError("source runtime already contains AGILLM attention v1")

    counts: Dict[str, int] = {}

    class_marker = "class TuneableAttentionMHA(nn.Module):\n"
    if source.count(class_marker) != 1:
        raise RuntimeError("expected exactly one TuneableAttentionMHA class")
    source = source.replace(
        class_marker,
        folded_backend_source(backend_source, backend_sha) + class_marker,
        1,
    )
    counts["folded_backend"] = 1

    class_pos = source.index(class_marker)
    start = source.index("        attn_mask = mask\n", class_pos)
    end_marker = '        elif self.attn_backend == "sublinear":\n'
    end = source.index(end_marker, start)
    if end - start > 8000:
        raise RuntimeError("attention dispatch region was unexpectedly large")
    old_region = source[start:end]
    if old_region.count("F.scaled_dot_product_attention") < 1:
        raise RuntimeError("attention dispatch did not contain the reference SDPA call")
    source = source[:start] + dispatch_block() + source[end:]
    counts["attention_dispatch"] = 1

    old = '''        causal = _agillm41_sys.modules[__name__].causal_mask(
            seq_len,
            structured=_agillm41_sys.modules[__name__].use_structured_masks(args),
        )'''
    new = '''        causal = _agillm41_sys.modules[__name__]._dblock_causal_mask(
            args, seq_len
        )'''
    source, count = replace_exact(source, old, new, 1, "fullstack causal")
    counts["fullstack_causal_call"] = count

    source, count = replace_exact(
        source,
        "M.causal_mask(T, structured=M.use_structured_masks(args))",
        "M._dblock_causal_mask(args, T)",
        3,
        "DBlock causal T",
    )
    counts["dblock_causal_t_calls"] = count

    source, count = replace_exact(
        source,
        "M.causal_mask(seq_len, structured=M.use_structured_masks(args))",
        "M._dblock_causal_mask(args, seq_len)",
        1,
        "DBlock causal seq_len",
    )
    counts["dblock_causal_seq_call"] = count

    old_sat = '''        fixed_sat_mask = M.sat_mask(
            seq_len, block=2, structured=M.use_structured_masks(args)
        )'''
    new_sat = '''        fixed_sat_mask = M._dblock_sat_mask(
            args, seq_len, block=2
        )'''
    source, count = replace_exact(source, old_sat, new_sat, 1, "fullstack fixed SAT")
    counts["fullstack_sat_call"] = count

    source, count = replace_exact(
        source,
        "smask = M.sat_mask(T, structured=M.use_structured_masks(args))",
        "smask = M._dblock_sat_mask(args, T)",
        1,
        "DBlock SAT",
    )
    counts["dblock_sat_call"] = count

    sat_def = "def sat_mask(n, block=SAT_BLOCK, structured: bool = False):\n"
    if source.count(sat_def) != 1:
        raise RuntimeError("expected exactly one sat_mask definition")
    source = source.replace(sat_def, helper_block() + sat_def, 1)
    counts["mask_helpers"] = 2

    # Compile without importing or executing the runtime.  This catches syntax,
    # future-import, and indentation failures while leaving all trainer state alone.
    compile(source, "<agillm-attention-runtime-candidate>", "exec")

    required = {
        BEGIN_SENTINEL: 1,
        END_SENTINEL: 1,
        CALL_SENTINEL: 1,
        "def _dblock_causal_mask(args, n):": 1,
        "def _dblock_sat_mask(args, n, block=SAT_BLOCK):": 1,
    }
    for marker, expected in required.items():
        observed = source.count(marker)
        if observed != expected:
            raise RuntimeError(
                "post-patch marker %r expected %d, got %d" %
                (marker, expected, observed)
            )

    return source, counts


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--backend",
        type=Path,
        default=repo_root / "agillm_attention" / "backend.py",
    )
    parser.add_argument("--source-sha256", default="")
    parser.add_argument("--receipt", type=Path, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    source_path = args.source.resolve()
    output_path = args.output.resolve()
    backend_path = args.backend.resolve()

    if source_path == output_path:
        raise SystemExit("refusing in-place runtime modification")
    if not source_path.is_file():
        raise SystemExit("source runtime does not exist: %s" % source_path)
    if not backend_path.is_file():
        raise SystemExit("backend source does not exist: %s" % backend_path)

    source_bytes = source_path.read_bytes()
    source_sha = sha256_bytes(source_bytes)
    expected_sha = str(args.source_sha256 or "").strip().lower()
    if expected_sha and source_sha != expected_sha:
        raise SystemExit(
            "source SHA256 mismatch: expected %s, got %s" %
            (expected_sha, source_sha)
        )

    backend_bytes = backend_path.read_bytes()
    backend_sha = sha256_bytes(backend_bytes)
    candidate, counts = patch_runtime(
        source_bytes.decode("utf-8"),
        backend_bytes.decode("utf-8"),
        backend_sha,
    )
    output_bytes = candidate.encode("utf-8")
    output_sha = sha256_bytes(output_bytes)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    old_mode = stat.S_IMODE(source_path.stat().st_mode)
    fd, tmp_name = tempfile.mkstemp(
        prefix=output_path.name + ".", suffix=".tmp", dir=str(output_path.parent)
    )
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(output_bytes)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(tmp_name, old_mode)
        os.replace(tmp_name, output_path)
    finally:
        if os.path.exists(tmp_name):
            os.unlink(tmp_name)

    receipt_path = (
        args.receipt.resolve()
        if args.receipt is not None
        else output_path.with_suffix(output_path.suffix + ".receipt.json")
    )
    receipt = {
        "schema": BUILDER_SCHEMA,
        "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "source": str(source_path),
        "source_sha256": source_sha,
        "backend": str(backend_path),
        "backend_sha256": backend_sha,
        "output": str(output_path),
        "output_sha256": output_sha,
        "output_bytes": len(output_bytes),
        "replacement_counts": counts,
        "production_activated": False,
        "notes": [
            "single-file candidate only",
            "no checkpoint transformation",
            "no trainer, supervisor, or watchdog mutation",
        ],
    }
    receipt_path.parent.mkdir(parents=True, exist_ok=True)
    receipt_path.write_text(json.dumps(receipt, indent=2, sort_keys=True) + "\n")
    print(json.dumps(receipt, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
